version: '3'
services:
  db:
    image: postgres:14
    container_name: emp-manage-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andy9999
      - POSTGRES_DB=postgres
  api:
    container_name: emp-manage-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9991:9990"
    depends_on:
      - db
