version: '3.9'
services:
  db:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andy9999
      - POSTGRES_DB=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "9991:9990"
    depends_on:
      - db
