version: '3'
services:
  db:
    image: postgres:14
    container_name: java-ee-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andy9999
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"