version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "5432:5432"
